FROM node:20-alpine AS builder

WORKDIR /app/

COPY ./frontend .

WORKDIR /app/frontend

ARG BACKEND_URL

RUN mkdir -p /app/frontend/src/environment && \
    echo "export const environment = { " > /app/frontend/src/environment/environment.ts && \    
    echo "    production: true," >> /app/frontend/src/environment/environment.ts && \
    echo "    BACKEND_URL: '${BACKEND_URL}'" >> /app/frontend/src/environment/environment.ts && \
    echo "};" >> /app/frontend/src/environment/environment.ts
# RUN npm install

# RUN npm run build --prod 

# FROM nginx:1.29.4-alpine

# COPY --from=builder /app/dist/angular-conduit /usr/share/nginx/html

# EXPOSE 80

# ENTRYPOINT [ "nginx", "-g", "daemon off;" ]