FROM python:3.5.2-alpine

WORKDIR /app

ARG ALLOWED_HOST

COPY ./backend ./backend

COPY entrypoint.sh .

WORKDIR /app/backend

RUN pip install -r requirements.txt

EXPOSE 5000

RUN chmod +x /app/entrypoint.sh

RUN echo "ALLOWED_HOST=${ALLOWED_HOST}" >> /app/backend/conduit/.env

ENTRYPOINT ["/bin/sh", "/app/entrypoint.sh"]