services:
  frontend:
    build: ./Dockerfile.frontend
    ports: 
      - "4000:80"
    depends_on:
      - backend
  backend:
    build: ./Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/app

volumes:
  backend-data: