FROM python:3.5.2-alpine

WORKDIR /app

COPY ./backend ./backend

COPY entrypoint.sh .

WORKDIR /app/backend

RUN pip install -r requirements.txt

EXPOSE 5000

RUN chmod +x /app/entrypoint.sh

ENTRYPOINT ["/bin/sh", "/app/entrypoint.sh"]