services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports: 
      - "4000:80"
    depends_on:
      - backend
    env_file:
      - example.env
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/app
    env_file:
      - example.env
volumes:
  backend-data: