FROM node:20-alpine AS builder

WORKDIR /app

COPY . .

WORKDIR /app/frontend

RUN npm install

RUN npm run build

FROM nginx:1.29.4-alpine

COPY --from=builder /app/frontend/dist /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]