FROM node:20-alpine AS builder

WORKDIR /app/

COPY ./frontend .

WORKDIR /app/src

ARG BACKEND_URL=http://localhost:5000

RUN mkdir -p environments && \
    echo "export const environment = { " > environments/environment.ts && \    
    echo "    production: true," >> environments/environment.ts && \
    echo "    BACKEND_URL: '${BACKEND_URL}'" >> environments/environment.ts && \
    echo "};" >> environments/environment.ts && \
    npm install && \
    npm run build

FROM nginx:1.29.4-alpine

COPY --from=builder /app/dist/angular-conduit /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]