name: Deployment
on: 
  push:
    branches:
      - main
      - auto-deploment
  pull_request:
    branches:
      - main
      - auto-deploment
      
jobs:
  deployment:
    runs-on: ubuntu-24.04
    name: Deploy
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          submodules: true
          fetch-depth: 0
      - name: Create env file
        run: |
          cat > .env <<EOF
          BACKEND_URL=${{ secrets.BACKEND_URL }}
          ALLOWED_HOSTS=${{ secrets.HOST }}
          CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
          DEBUG=${{ secrets.DEBUG }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          EOF
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker images
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          docker build -t ghcr.io/${REPO_LOWER}/backend:${COMMIT_HASH} -f ./Dockerfile.backend .
          docker build -t ghcr.io/${REPO_LOWER}/frontend:${COMMIT_HASH} --build-arg BACKEND_URL=${{ secrets.BACKEND_URL }} -f ./Dockerfile.frontend .
          docker push ghcr.io/${REPO_LOWER}/backend:${COMMIT_HASH}
          docker push ghcr.io/${REPO_LOWER}/frontend:${COMMIT_HASH}
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: ".env, docker-compose.yml"
          target: "/tmp/"
      - name: Execute commands via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            mkdir -p ${{ secrets.DIRECTORY }}
            cd ${{ secrets.DIRECTORY }}
            mv /tmp/.env /tmp/docker-compose.yml ${{ secrets.DIRECTORY }}
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker-compose rm -f
            docker-compose pull
            docker-compose up -d